#!/bin/bash

if [ ! -e sensor ]; then
   make
fi

case $1 in

  demo)

   ID=17190 # Compendium ID for walking
   process=training
   data_path=../data/Phase_2/csv_format/Craig/Craig_Walking_tredmil.csv
   ref_path=../data/ref_data
   N=1

   ./sensor $process $ID $data_path $corr_path $N $ref_path

   process=data
   data_path=../data/Phase_2/csv_format/Craig/Craig_Walking_tredmil.csv
   corr_path=../data/corr
   ref_path=../data/ref_data17190
   N=1

   ./sensor $process $ID $data_path $corr_path $N $ref_path
   ;;

  special)

   ID=17190
   process=training
   data_path=../data/Phase_2/csv_format/Craig/walking/2015-01-03-05-46-14.csv
   corr_path=../data/corr
   ref_path=../data/ref_data
   N=1

   ./sensor $process $ID $data_path $corr_path $N $ref_path

   ID=01015
   process=training
   data_path=../data/Phase_1/Craig_Bicycling_Kin.csv
   corr_path=../data/corr
   ref_path=../data/ref_data
   N=1

   ./sensor $process $ID $data_path $corr_path $N $ref_path

   process=data
   data_path=../data/Phase_2/csv_format/Craig/walking/2015-01-03-05-55-45.csv
   corr_path=../data/corr
   ref_path1=../data/ref_data17190
   ref_path2=../data/ref_data1015
   N=2

   ./sensor $process $ID $data_path $corr_path $N $ref_path1 $ref_path2
   ;;

  *)
   echo "No run case specified"
   echo "Try ./run demo"
   echo "or  ./run special"
esac
