#!/bin/bash

if [ ! -e main ]; then
   make
fi

ID=17190

process=reference
data_path=../data/Craig_Walking_tredmil.csv
ref_path=../data/ref_data$ID

./main $process $ID $data_path $ref_path

process=data
data_path=../data/Craig_Walking_tredmil.csv
ref_path=../data/ref_data$ID

./main $process $ID $data_path $ref_path
