#!/bin/bash

if [ ! -e sensor ]; then
   make
fi

if [ ! -d output ]; then
   mkdir -v output
fi

input_file=input_train_demo
./train $input_file

input_file=input_demo
refs_path=ref_demo
./sensor $input_file $refs_path
