#!/bin/bash

if [ ! -e sensor ]; then
   make
fi

if [ ! -d output ]; then
   mkdir -v output
fi

input_file=input_train_demo
./train $input_file

input_file=input_demo
#input_file=input_demo_test
refs_path=ref_demo
./sensor $input_file $refs_path


# used to help simplify using diff
cat output/activity_demo > output/all_of_it
cat output/correlations_demo17190 >> output/all_of_it
cat output/energy_demo >> output/all_of_it
cat output/power_demo >> output/all_of_it
cat output/ref_data17190 >> output/all_of_it
